[tool.poetry]
name = "pr-reviews"
version = "0.1.0"
description = ""
authors = ["ghinks <ghinks@yahoo.com>"]
license = "Apache"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gql = "^3.5.0"
aiohttp = "^3.11.2"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
