name: Python package

on: [push, workflow_dispatch, pull_request]

jobs:
  build:
    runs-on:
      ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          pip install poetry
          poetry install
      - name: run the black linter
        run: |
          python -m black --check .